---
- name: Install nyancat
  apt:
    name: nyancat
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install nyancat unit
  copy:
    src: files/nyancat-tty.service
    dest: /etc/systemd/system/nyancat-tty.service

- name: Disable tty
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - getty
    - getty@tty1
  ignore_errors: True

- name: Install nyancat unit
  systemd:
    name: nyancat-tty
    enabled: yes
    state: started
    daemon_reload: yes
